# Generated by Django 4.2.18 on 2025-03-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('food', 'Food'), ('health', 'Health'), ('business', 'Business'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(default='', help_text='Enter tags separated by commas', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
    ]
